import { LanguagePack } from '../types';

export const translations: Record<'id' | 'en', LanguagePack> = {
  id: {
    dashboard: "Dasbor",
    projects: "Proyek & Anggaran",
    materials: "Log Material",
    progressPhotos: "Foto Progres",
    hrAttendance: "SDM & Absensi",
    deployments: "Status Deploy",
    otherExpenses: "Pengeluaran Lain",
    slipGaji: "Slip Gaji",
    attendance: "Absensi",
    kasbon: "Kasbon",
    overtime: "Lembur",
    addProject: "Tambah Proyek",
    projectName: "Nama Proyek",
    budget: "Anggaran",
    startDate: "Tanggal Mulai",
    endDate: "Tanggal Selesai",
    actions: "Aksi",
    save: "Simpan",
    cancel: "Batal",
    addMaterial: "Catat Material",
    materialIn: "Material Masuk",
    materialOut: "Material Keluar",
    itemName: "Nama Barang",
    qty: "Jumlah",
    unit: "Satuan",
    price: "Harga",
    total: "Total",
    note: "Catatan",
    addPhoto: "Ambil Foto Progress",
    watermark: "Watermark Otomatis",
    gpsRequired: "Sertakan GPS",
    slipGajiTitle: "Slip Gaji Karyawan",
    netSalary: "Gaji Bersih",
    totalLembur: "Total Lembur",
    totalKasbon: "Total Potongan Kasbon",
    invoiceAlert: "Pengingat Invoice Jatuh Tempo",
    uploadQueue: "Antrean Upload Offline",
    offlineMode: "Bekerja Offline",
    syncCloud: "Sinkronisasi Cloud",
    encrypted: "Enkripsi End-to-End",
    shareWA: "Bagikan Laporan Harian ke WhatsApp",
    selectProject: "Pilih Proyek",
    dailyReport: "Laporan Harian",
    role: "Peran Pengguna",
    admin: "Administrator",
    mandor: "Mandor Lapangan",
    guest: "Tamu / Owner",
    theme: "Tema",
    language: "Bahasa"
  },
  en: {
    dashboard: "Dashboard",
    projects: "Projects & Budget",
    materials: "Material Log",
    progressPhotos: "Progress Photos",
    hrAttendance: "HR & Attendance",
    deployments: "Deploy Status",
    otherExpenses: "Other Expenses",
    slipGaji: "Payslip",
    attendance: "Attendance",
    kasbon: "Advance Payment",
    overtime: "Overtime",
    addProject: "Add Project",
    projectName: "Project Name",
    budget: "Budget",
    startDate: "Start Date",
    endDate: "End Date",
    actions: "Actions",
    save: "Save",
    cancel: "Cancel",
    addMaterial: "Log Material",
    materialIn: "Incoming Material",
    materialOut: "Outgoing Material",
    itemName: "Item Name",
    qty: "Qty",
    unit: "Unit",
    price: "Price",
    total: "Total",
    note: "Note",
    addPhoto: "Capture Progress Photo",
    watermark: "Auto Watermark",
    gpsRequired: "Include GPS",
    slipGajiTitle: "Employee Payslip",
    netSalary: "Net Salary",
    totalLembur: "Total Overtime",
    totalKasbon: "Total Advance Deductions",
    invoiceAlert: "Invoice Due Reminders",
    uploadQueue: "Offline Upload Queue",
    offlineMode: "Working Offline",
    syncCloud: "Cloud Synchronized",
    encrypted: "End-to-End Encrypted",
    shareWA: "Share Daily Report to WhatsApp",
    selectProject: "Select Project",
    dailyReport: "Daily Report",
    role: "User Role",
    admin: "Administrator",
    mandor: "Site Foreman",
    guest: "Guest / Owner",
    theme: "Theme",
    language: "Language"
  }
};
